AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 instance automation for our development environment"
Metadata: {}

Parameters: 
  devwebserverkeyname:
    Description: please select a keypair
    Type: AWS::EC2::KeyPair::KeyName
  EnvironmentName:
    Description: Please select your choice Env.
    Type: String
    AllowedValues:
      - Dev
      - Prod
      - Stage

Mappings: 
  devwebservergoldenAMImap:
    us-east-1:
      goldenAMI: ami-0fc5d935ebf8bc3bc
    us-east-2:
      goldenAMI: ami-0e83be366243f524a
    us-west-1:
      goldenAMI: ami-0cbd40f694b804622
    us-west-2:
      goldenAMI: ami-0efcece6bed30fd98

Conditions:
  CreateDevStageProdResources:
    !Equals [!Ref EnvironmentName, Prod]

Resources: 
  DevWebserver1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref devwebserverkeyname
      ImageId: !FindInMap [ devwebservergoldenAMImap, !Ref 'AWS::Region', goldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash 
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags:
        - Key: Name
          Value: DevWebserver1

  DevWebserver2:
    Condition: CreateDevStageProdResources
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref devwebserverkeyname
      ImageId: !FindInMap [ devwebservergoldenAMImap, !Ref 'AWS::Region', goldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash 
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags:
        - Key: Name
          Value: DevWebserver2
          
  DevWebserver3:
    Condition: CreateDevStageProdResources
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref devwebserverkeyname
      ImageId: !FindInMap [ devwebservergoldenAMImap, !Ref 'AWS::Region', goldenAMI ]
      InstanceType: t2.micro
      Monitoring: true
      UserData: !Base64 |
        #!/bin/bash 
        sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags:
        - Key: Name
          Value: DevWebserver3        

Outputs: {}