AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 instance automation for development environment"
Metadata: {}

Parameters: {}

Mappings: {}

Conditions: {}

Resources: 
  DevWebserver:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: New1-KeyWin
      ImageId: ami-053b0d53c279acc90
      InstanceType: t2.micro
      Monitoring: true
      SecurityGroupIds:
        - sg-0890166182cf5ed89 
      UserData: !Base64 |
        #!/bin/bash
        # sudo su
        apt update -y
        apt -y install apache2
        systemctl start apache2
        systemctl enable apache2
        apt install wget -y
        wget https://github.com/awanmbandi/google-cloud-projects/raw/jjtech-flix-app/jjtech-streaming-application-v1.zip 
        apt install unzip -y
        unzip jjtech-streaming-application-v1.zip
        rm -f /var/www/html/index.html
        cp -rf jjtech-streaming-application-v1/* /var/www/html/
      Tags:
        - Key: Name
          Value: DevWebserver

Outputs: {} 